nama = str("Warda Amalia")
nim = int(20250040005)
umur = int(19)
TinggiBadan = float(157)
Status = list(("Aktif", "Tidak Aktif"))
print (nama)
print (nim)
print (umur)
print (TinggiBadan)
print (Status)
print("\n")

nama = input ("Masukkan Nama: ") 
NIM = int(input("Masukkan NIM:"))
prodi = input ("Masukkan prodi: ")
Umur = int(input("Masukkan Umur:"))
Status = str(input("Masukkan Status (Aktif/Tidak Aktif):"))
if Status == "aktif":
    print("Status Aktif")
else :
    print("tidak aktif")
print("Nama:", nama)
print("NIM:", NIM)
print("prodi:", prodi)
print("Umur:", Umur)
print("Status:", Status)
  